# Generated by Django 5.2.6 on 2026-01-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
